// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmazD6QtWGsdpKyObMy5sHjrFAcoddYaI',
    appId: '1:462260018579:web:d716dc2570d7ded50d5c66',
    messagingSenderId: '462260018579',
    projectId: 'redbutton-d493c',
    authDomain: 'redbutton-d493c.firebaseapp.com',
    storageBucket: 'redbutton-d493c.appspot.com',
    measurementId: 'G-J9PSNR9SCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV8ExHKUtNJRze2kXWUVJ5N6lE3PByi0U',
    appId: '1:462260018579:android:552ca36b28f5e2fa0d5c66',
    messagingSenderId: '462260018579',
    projectId: 'redbutton-d493c',
    storageBucket: 'redbutton-d493c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVpgOf5CE1c_MGAX_BTxuuG9WK1SrYlo8',
    appId: '1:462260018579:ios:85e0455952dab27b0d5c66',
    messagingSenderId: '462260018579',
    projectId: 'redbutton-d493c',
    storageBucket: 'redbutton-d493c.appspot.com',
    iosClientId: '462260018579-sers04m78jmr8oisjj6ofb02e4el1dlv.apps.googleusercontent.com',
    iosBundleId: 'com.redbutton.providerexampleIOS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVpgOf5CE1c_MGAX_BTxuuG9WK1SrYlo8',
    appId: '1:462260018579:ios:80176930ea2848f70d5c66',
    messagingSenderId: '462260018579',
    projectId: 'redbutton-d493c',
    storageBucket: 'redbutton-d493c.appspot.com',
    iosClientId: '462260018579-kui0u08t5sat1386rkvck8iigfdkgcuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerexample',
  );
}
